### ISSUE TITLE
digitalWrite(LED_BUILTIN, LOW) turns on the led

### ISSUE THREAD

**Issue by AFimiani** [Freenove/Freenove_Ultimate_Starter_Kit_for_ESP32#9]
Following the "project 0.1 Blink" in the C tutorial, I observed an unexpected behavior in the LED control using the digitalWrite function. According to the tutorial, digitalWrite(LED_BUILTIN, LOW); is supposed to turn off the LED, while digitalWrite(LED_BUILTIN, HIGH); should turn it on. However, the actual behavior is the opposite. I would like to know if this is a normal behavior or if there might be an error in some driver. 

**Environment**:
Operating System: Ubuntu 22.04.3 LTS
Installed drivers: CH340

**Additional Information**:
I have verified this behavior by commenting out each function in turn and observing the LED's response.

**Comment by Zhentao-Lin** [comment]
The positive led is connected to 3.3V and the negative LED is connected to IO2.
